refresh_rate: 5 seconds

appenders:
  console:
    kind: console
    encoder:
      pattern: "{M}:{L} {h(<{l}>)} {m}{n}"
    filters:
      - kind: threshold
        level: info
  file:
    kind: file
    path: "logs/debug.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)(utc)} | {M}:{L} {h(<{l}>)} {m}{n}"

root:
  appenders:
  - console

loggers:
  stegosaurusography:
    level: trace
    appenders:
      - file
    additive: true